# Generated by Django 4.2.4 on 2023-09-04 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('description_short', models.CharField(db_index=True, max_length=500, verbose_name='Короткое описание')),
                ('description_long', models.TextField(verbose_name='Описание')),
                ('longitude', models.DecimalField(decimal_places=13, max_digits=15, verbose_name='Долгота')),
                ('latitude', models.DecimalField(decimal_places=13, max_digits=15, verbose_name='Широта')),
            ],
            options={
                'verbose_name': 'Места',
                'verbose_name_plural': 'Места',
            },
        ),
    ]
