# Generated by Django 4.2.4 on 2023-09-06 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_alter_point_latitude_alter_point_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Фото')),
                ('position', models.IntegerField(db_index=True, unique=True, verbose_name='Позиция')),
                ('to_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='places.point', verbose_name='К локации')),
            ],
            options={
                'verbose_name': 'Фоторгафия',
                'verbose_name_plural': 'Фотографии',
            },
        ),
    ]
