# Generated by Django 4.2.4 on 2023-09-17 09:39

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_alter_image_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['position'], 'verbose_name': 'Фоторгафия', 'verbose_name_plural': 'Фотографии'},
        ),
        migrations.AlterField(
            model_name='point',
            name='description_long',
            field=tinymce.models.HTMLField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='point',
            name='description_short',
            field=models.TextField(db_index=True, verbose_name='Короткое описание'),
        ),
    ]
