# Generated by Django 4.2.4 on 2023-09-17 09:57

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_alter_image_options_alter_point_description_long_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='position',
            field=models.IntegerField(blank=True, db_index=True, default=0, null=True, verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='point',
            name='description_long',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='point',
            name='description_short',
            field=models.TextField(blank=True, db_index=True, null=True, verbose_name='Короткое описание'),
        ),
    ]
