# Generated by Django 4.2.4 on 2023-09-17 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_alter_image_position_alter_point_description_long_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='point',
            old_name='description_long',
            new_name='long_description',
        ),
        migrations.RenameField(
            model_name='point',
            old_name='description_short',
            new_name='short_description',
        ),
    ]
