# Generated by Django 4.2.4 on 2023-09-17 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_rename_description_long_point_long_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['to_point__title'], 'verbose_name': 'Фоторгафия', 'verbose_name_plural': 'Фотографии'},
        ),
        migrations.AlterField(
            model_name='point',
            name='title',
            field=models.CharField(max_length=150, unique=True, verbose_name='Название'),
        ),
    ]
